spring:
  datasource:
    initialization-mode: never
    schema: classpath:sql/member.sql, classpath:sql/person.sql

    url: jdbc:mysql://localhost:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
