spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/local
      username: sa
      password: 
